### ISSUE TITLE
drone-scp error:  Process exited with status 1

### ISSUE THREAD

**Issue by hasanisaeed** [appleboy/scp-action#108]
### Config:

```sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy on server
      uses: appleboy/scp-action@7af00892de6f8397c5c3393cfb3b32ae7f91b94b
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "test"
        target: ${{ secrets.PATH }}

```

### Error:

```
scp file to server.
create folder 
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file bGmzPUYYet.tar.gz
20[23](https://github.com/example/actions/runs/4656764466/jobs/8240700531#step:4:24)/04/10 10:46:10 Process exited with status 1
```

**Comment by appleboy** [comment]
@hasanisaeed your remote server OS version?

**Comment by appleboy** [comment]
@hasanisaeed Please help to try the `appleboy/scp-action@209e8c05e0492f6ed6fe8a22dfcaefb083c4cf35` version

**Comment by hasanisaeed** [comment]
@appleboy 
I'm using `Ubuntu 22.04`

**Comment by hasanisaeed** [comment]
New config:

```bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy on server
      uses: appleboy/scp-action@209e8c05e0492f6ed6fe8a22dfcaefb083c4cf35
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "test"
        target: ${{ secrets.PATH }}
```

Result:

```
tar all files into /tmp/lZCRHpSabJ.tar.gz
tar: removing leading '/' from member names
scp file to server.
create folder 
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file lZCRHpSabJ.tar.gz
20[23](https://github.com/example/actions/runs/4657011751/jobs/8241186122#step:7:24)/04/10 11:[26](https://github.com/.../actions/runs/4657011751/jobs/8241186122#step:7:27):05 Process exited with status 1

```

**Comment by hasanisaeed** [comment]
Yesterday, they were working well. It seems that with the new update, this issue has occurred.
Why am I getting the same results for the previous versions (v0.1.3) as well?

**Comment by hasanisaeed** [comment]
![Screenshot from 2023-04-10 22-27-53](https://user-images.githubusercontent.com/20496196/230973658-abaa80cd-c1d0-4111-be3e-f924c9386fbe.png)

**Comment by hasanisaeed** [comment]
![Screenshot from 2023-04-10 22-32-35](https://user-images.githubusercontent.com/20496196/230974630-a5727e51-b540-4cfd-ace3-162f33a42fc8.png)

for v0.1.3:

tar: removing leading '/' from member names
tar all files into /tmp/3879663452/LsLBRAdcLy.tar
scp file to server.
create folder 
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file LsLBRAdcLy.tar
[20](https://github.com/ah-ryca/mine-load-management-client/actions/runs/4660337395/jobs/8248278957#step:7:21)[23](https://github.com/ah-ryca/mine-load-management-client/actions/runs/4660337395/jobs/8248278957#step:7:24)/04/10 19:02:03 Process exited with status 1

**Comment by appleboy** [comment]
@hasanisaeed Can you provide the log with the timestamp using the following version

`appleboy/scp-action@209e8c05e0492f6ed6fe8a22dfcaefb083c4cf35`

You will see the output log

![image](https://user-images.githubusercontent.com/21979/231035503-cde64f92-7300-4381-bed6-fe854db72be3.png)

new log:

> remote server os type is unix

**Comment by hasanisaeed** [comment]
![Screenshot from 2023-04-11 08-13-22](https://user-images.githubusercontent.com/20496196/231058319-a8a3bc0b-774d-48da-b2f7-97aa362e9b54.png)

**Comment by appleboy** [comment]
@hasanisaeed What is your `target` setting?
