### ISSUE TITLE
Target "~" is creating a new folder - regression

### ISSUE THREAD

**Issue by jdetaeye** [appleboy/scp-action#112]
We have been using scp-action for quite some time now.  Very happy about it and very grateful to its developer community.

The recent changes have broken our github action. It looks like when you specify as target ~ or ~/somefolder/ it creates a new folder called ~ in the home directory. In previous releases it just referred to the home folder.

Not sure whether this is a bug or feature. In any case it's a behavior change I wanted to report.

**Comment by appleboy** [comment]
@jdetaeye I got your point. I will take it.

**Comment by appleboy** [comment]
ref: https://github.com/appleboy/scp-action/issues/85

**Comment by appleboy** [comment]
@jdetaeye Please use the stable version https://github.com/appleboy/scp-action/releases/tag/v0.1.4 first.

**Comment by appleboy** [comment]
@jdetaeye Please try the `master` version.
