### ISSUE TITLE
Missing - script in action

### ISSUE THREAD

**Issue by devops-saffranlabs** [appleboy/scp-action#114]
We are facing issue after last update on action. please let me know what i can do other then   "script"  ?

Warning: Unexpected input(s) 'script', valid inputs are ['entryPoint', 'args', 'host', 'port', 'username', 'password', 'timeout', 'command_timeout', 'key', 'key_path', 'passphrase', 'fingerprint', 'use_insecure_cipher', 'target', 'source', 'rm', 'debug', 'strip_components', 'overwrite', 'tar_tmp_path', 'proxy_host', 'proxy_port', 'proxy_username', 'proxy_password', 'proxy_passphrase', 'proxy_timeout', 'proxy_key', 'proxy_key_path', 'proxy_fingerprint', 'proxy_use_insecure_cipher']

**Comment by devops-saffranlabs** [comment]
its belong to ssh-action...

and its giving error at the end. 
Error: can't connect without a private SSH key or password

**Comment by devops-saffranlabs** [comment]
v0.1.3 have perfectly working with ssh_key
but v0.1.4 not working with ssh_key for scp-action.

**Comment by mbcodepl** [comment]
I have the same issue with master branch. v0.1.4 is working fine for me.

**Comment by appleboy** [comment]
@mbcodepl @devops-saffranlabs Please post your config. I refactor the env variable in the master version. Thnaks.

**Comment by appleboy** [comment]
See the documentation

![image](https://user-images.githubusercontent.com/21979/232262013-dffd76e9-01c0-43bb-b1cc-48261164835e.png)

scp-action and ssh-action doesn't support `ssh_key` parameter

**Comment by appleboy** [comment]
Please post your question to ssh-action issue list.

**Comment by devops-saffranlabs** [comment]
That is my actions i have used 0.1.3 then it works but not work on master neither on 0.1.4


- uses: actions/checkout@v1
    - name: STAGE - Laravel Code copying to AWS server
      if: github.ref == 'refs/heads/stage'
      uses: appleboy/scp-action@v0.1.3
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/mnt/data/stage.example.com/htdocs"
        overwrite: true
