### ISSUE TITLE
How to handle file ownership

### ISSUE THREAD

**Issue by strebl** [appleboy/scp-action#12]
The ownership of the files we deploy is wrong. Is it possible for you to add an option to set owner (user and group) after deployment?

**Comment by appleboy** [comment]
What is your use case? Why you need to change the ownership after deploying? I think it always aligns with the deploy account.

**Comment by strebl** [comment]
Because the deploy account is not the same user in this case. For example the deploy account is "deploy" and the webserver is running under www-data.

**Comment by appleboy** [comment]
maybe you should use the `ssh-action` to change the ownership?

**Comment by strebl** [comment]
Ah I didn't see that action. I'll use that, thx!
