### ISSUE TITLE
How to copy only source file without his directory

### ISSUE THREAD

**Issue by s-kraynev** [appleboy/scp-action#128]
Hi. I try to use action in the following way
```   - name: Copy my file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "infra/my_file.yml"
        target: "dest_directory"
```

I expected, that it will create the following structure:
`dest_directory/my_file.yml`

however, I get the different result like:
`dest_directory/infra/my_file.yml`

Is it possible to ignore "infra" in the source somehow? 

if I move my_file.yml on the same level as "infra" directory - action works as expected.

**Comment by GuDeBin** [comment]
Same issue

**Comment by dppo** [comment]
Same issue

**Comment by AlexPhyzik** [comment]
Use strip_components: 1
It remove the firts leading path element in source path.

**Comment by s-kraynev** [comment]
@AlexPhyzik thank you very much. It works for me.
