### ISSUE TITLE
How can i believe the security behind this?

### ISSUE THREAD

**Issue by muthugit** [appleboy/scp-action#13]
Even I am saving the SSHKEY on the secret, how I can ensure that the overall cycle is secure one. Means, the theft of the SSHKEY. Can you please confirm that, our SSHKEY is secure one and not to share with anybody?

**Comment by appleboy** [comment]
You can trust the plugin which doesn't store your SSH Key. But you can't trust the GitHub Actions.

**Comment by rivanbello** [comment]
@appleboy why can't we trust Github Actions? Is there something we should be wary of?

**Comment by appleboy** [comment]
@rivanbello because GitHub stores your ssh private key and password and you don't know how it works.
