### ISSUE TITLE
Tmp creation timestamp issue

### ISSUE THREAD

**Issue by manico** [appleboy/scp-action#16]
Hello, I have successfully build job but no files on target server.
In action log I got this:

```
tar all files into /tmp/487751054/cO92IVCaby.tar
scp file to server.
create folder ***
untar file cO92IVCaby.tar
error:  tar: .: time stamp 2020-04-14 11:48:00 is 3.417555878 s in the future
remove file cO92IVCaby.tar
```

Isn't job supposed to fail if some error happens?
Anyways, do you know how to get around this?

**Comment by mattbag** [comment]
Ehy check the files go in the correct folder. It doesn't look like a fail
