### ISSUE TITLE
Can we send the entire source folder?

### ISSUE THREAD

**Issue by kimk1029** [appleboy/scp-action#34]
I am going to send the entire folder using scp. But there's an error. Is it because I put the folder name in the source parameter?

The error is as follows.

`
...
..
tar all files into /tmp/224126534/uNyJo54J6q.tar
tar: empty archive
exit status 1`

**Comment by kimk1029** [comment]
I saw one of the answers you registered on the issue and the bug was corrected. But it's not the way I wanted it.
You recommend sending the entire current folder with a "*" on the source. But after building, I want to send the result that was built using the scp module, but it is not t

**Comment by appleboy** [comment]
@kimk1029 Post your config first.

**Comment by joeyorlando** [comment]
`source: '*'`  should work (See [here](https://github.com/appleboy/drone-scp/blob/6d6124e8d8fd3defbee0aa892de28a28c64223ba/DOCS.md), this helped me)
![Screen Shot 2020-09-16 at 6 31 14 PM](https://user-images.githubusercontent.com/9406895/93399093-d4391300-f84a-11ea-91d6-cf19efba0164.png)

**Comment by appleboy** [comment]
See https://github.com/appleboy/scp-action/issues/33
