### ISSUE TITLE
Untar as SUDO?

### ISSUE THREAD

**Issue by VictorioBerra** [appleboy/scp-action#5]
Getting permission denied for the target. I assume it needs to untar as root? Any flag for that?

**Comment by appleboy** [comment]
@VictorioBerra Please grant permission for the deploy user account.

**Comment by yalamber** [comment]
@appleboy what permission do we need to grant deploy user?

**Comment by appleboy** [comment]
@yalamber 0755 and make sure the owner of the folder.
