### ISSUE TITLE
error copy file to dest: ***, error message: Process exited with status 1

### ISSUE THREAD

**Issue by saqibameen** [appleboy/scp-action#51]
It's a duplicate of #8. So I am getting this error:

tar all files into /tmp/745735171/nZiZOczyk2.tar
scp file to server.
2021/03/03 07:08:04 error copy file to dest: ***, error message: Process exited with status 1
drone-scp error:  error copy file to dest: ***, error message: Process exited with status 1

Can somebody help? I am trying to run it on self-hosted GH Actions.

**Comment by bad-mushroom** [comment]
I was just dealing with the same error when I found your issue. In my case it was because the directory I was SCP'ing the tar file to didn't exist. I didn't realize that SCP wouldn't create the directory 🤦 

Once I manually created the directory and confirmed my SSH user could write to it:

```
tar all files into /tmp/778239743/DMfN2w1Yep.tar
scp file to server.
create folder /var/apps/<appname>/releases/ed598f123cba02fdd3561c63fe4ca42afe8fe81a
untar file DMfN2w1Yep.tar
remove file DMfN2w1Yep.tar
===================================================
✅ Successfully executed transfer data to all host
===================================================
```

**Comment by matthew-williamson-sd** [comment]
Just as a tip for others coming across this: you also get this error if your user does not have a home directory. I believe the action first scps the file into the user's home directory, and then performs a move.

**Comment by gdevdeiv** [comment]
Tried all you said, same error. Any clues?

**Comment by pjaspinski** [comment]
I had the same issue and it was caused by insufficient user's permissions in target directory.

**Comment by Shekhar-Shivam** [comment]
I got this error when trying to scp via username and password.  I Tried the to SCP via SSH-KEYGEN  key pairs and it actually worked !!!

**Comment by hyoretsu** [comment]
Can't we skip the step that copies it to home folder? I have space available in the server I'm using, but not so much in my /home...
