### ISSUE TITLE
Cannot Copy to target server

### ISSUE THREAD

**Issue by agitnaeta** [appleboy/scp-action#60]
I try to copy from `Github Action` 
to my own server 
it returns 

--- 
File Github action 

-rw-r--r-- 1 runner docker  35M Aug 21 21:13 website.tar.gz

---

Destination On server
`/home/devops`

---

   source: "website.tar.gz"
    target: /home/devops

`/usr/bin/docker run --name c9e036e2e49b491a4248bcb1185f8ba10fbaad_48d887 --label c9e036 --workdir /github/workspace --rm -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PORT -e INPUT_PASSWORD -e INPUT_SOURCE -e INPUT_TARGET -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_PASSPHRASE -e INPUT_FINGERPRINT -e INPUT_USE_INSECURE_CIPHER -e INPUT_RM -e INPUT_DEBUG -e INPUT_STRIP_COMPONENTS -e INPUT_OVERWRITE -e INPUT_TAR_TMP_PATH -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_USE_INSECURE_CIPHER -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/linode-api/linode-api":"/github/workspace" c9e036:e2e49b491a4248bcb1185f8ba10fbaad
tar all files into /tmp/688257434/mGoqmJ9gpd.tar
scp file to server.
2021/08/21 21:13:20 error copy file to dest: ***, error message: Process exited with status 1
drone-scp error:  error copy file to dest: ***, error message: Process exited with status 1`

**Comment by matheusfrancisco** [comment]
I'm facing this same problem, if you know how to solve this, please could you post here @agitnaeta  ?

**Comment by profnandaa** [comment]
Looks like the server must be a docker linux server as the fine-print on the README states. Facing the same issue...

**Comment by RohitPrasadBhatt** [comment]
Did you try these ?
https://github.com/appleboy/scp-action/issues/29#issuecomment-927874463
https://github.com/appleboy/scp-action/issues/28#issuecomment-746647298
