### ISSUE TITLE
EOF error message: SHH copying to remote

### ISSUE THREAD

**Issue by PhathomComputing** [appleboy/scp-action#62]
![image](https://user-images.githubusercontent.com/38705713/134174868-26099b0e-73a9-4f66-bc78-b3bd3ed9dfb1.png)

**Comment by ethanclevenger91** [comment]
@PhathomComputing what did you end up doing to solve this?

**Comment by PhathomComputing** [comment]
@ethanclevenger91 It was quite some time ago, but i remember playing with the keys, i believe i did a complete wipe and from scratch created new keys between server and github, i also was using cpanel so there was a built in method to connect from the server side through the cpanel, but the corresponding keys had to be set in the github repo as well to match
