### ISSUE TITLE
Action Build fails; Docker build failed

### ISSUE THREAD

**Issue by jeffreylanters** [appleboy/scp-action#72]
Hi, I'm here to notify a problem. While using SCP Action 0.1.2, the Build steps fails due to a Docker error where Docker exits with error code 1 due to a bad gateway. I doubt this has anything to do with this action, but Docker seems to be up and running according to their [status page](https://status.docker.com).

![image](https://user-images.githubusercontent.com/3404617/146840351-5aaa4c01-c410-4279-992f-67bfc4d86b77.png)

**Comment by CervarlCG** [comment]
I am getting the same error

**Comment by CervarlCG** [comment]
Ok docker now show issues in their services

![Screen Shot 2021-12-20 at 16 44 09](https://user-images.githubusercontent.com/53922412/146842500-fe2f2e59-c3c3-49af-bab9-1f1819dec669.png)

**Comment by CervarlCG** [comment]
it's working now
