### ISSUE TITLE
missing source or target config

### ISSUE THREAD

**Issue by Lecarvalho** [appleboy/scp-action#9]
Hi, I received this error when trying to publish the files to server:

![image](https://user-images.githubusercontent.com/5149784/73264368-9c3c6d00-41a0-11ea-91b7-a41c099f9a43.png)

I'm using SSH configuration with the secrets key.

Can you please help me?
Thanks.

**Comment by appleboy** [comment]
Please upgrade to [the latest version](https://github.com/appleboy/scp-action/releases) and also see [the example](https://github.com/appleboy/scp-action#example).
