### ISSUE TITLE
drone-scp-error

### ISSUE THREAD

**Issue by nx-rohanparekh** [appleboy/scp-action#92]
I am trying to copy jar to remote server, but I am getting below error

create folder /***/servers/apache-tomcat-9.0.17/webapps/
drone-scp error:  /dev/mem: No such file or directory
/dev/mem: No such file or directory
TERM environment variable not set.

I have two questions based on the logs
1) why it says "create folder" although I already have that folder exist in remote location!
2) no exit code message, step just failed with drone-scp-error message

Remote server has CentOS 7 64bit OS

Thanks in advance

**Comment by appleboy** [comment]
Please post your config.

**Comment by appleboy** [comment]
@nx-rohanparekh your target config is `/dev/mem` ?

**Comment by nx-rohanparekh** [comment]
I had issue with mismatching of keys in known_host file. Issue is resolved

**Comment by gheysiell** [comment]
Same problem here, I have an Ubuntu VPS everything happens exactly in the same pipeline, but on the CentOS VPS it doesn't work
