### ISSUE TITLE
drone-scp error:  Process exited with status 1

### ISSUE THREAD

**Issue by hafidz98** [appleboy/scp-action#99]
I have error like these, how should i do? 
![image](https://user-images.githubusercontent.com/16932189/229130812-e366e7b4-202c-4e07-a818-0f73c660a375.png)
![image](https://user-images.githubusercontent.com/16932189/229131043-166906ac-2011-447b-bcb5-3ea0cf359bed.png)

my ci.yaml
![image](https://user-images.githubusercontent.com/16932189/229131201-0fae6c18-4ff9-4b83-8508-8df69b3b737b.png)

I try manually using ms powershell and its success
![image](https://user-images.githubusercontent.com/16932189/229132169-dcee8a5e-5a25-43cd-b7e9-ae8a87e2d135.png)

any suggestion? thanks

**Comment by appleboy** [comment]
Please try the following version

```diff
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
-     uses: appleboy/scp-action@master
+     uses: appleboy/scp-action@7af00892de6f8397c5c3393cfb3b32ae7f91b94b
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: "test"
```

**Comment by JohanDavidsson** [comment]
> Please try the following version
> 
> ```diff
>   build:
>     name: Build
>     runs-on: ubuntu-latest
>     steps:
>     - uses: actions/checkout@master
>     - name: copy file via ssh password
> -     uses: appleboy/scp-action@master
> +     uses: appleboy/scp-action@7af00892de6f8397c5c3393cfb3b32ae7f91b94b
>       with:
>         host: ${{ secrets.HOST }}
>         username: ${{ secrets.USERNAME }}
>         password: ${{ secrets.PASSWORD }}
>         port: ${{ secrets.PORT }}
>         source: "tests/a.txt,tests/b.txt"
>         target: "test"
> ```

Works for me, thanks!

**Comment by appleboy** [comment]
@JohanDavidsson You also can try the stable version `appleboy/scp-action@v0.1.4`

**Comment by sravankumarkeesara** [comment]
@appleboy  
I am facing a similar kind of error, but the process is creating ".tar.gz" files instead of just ".tar". This is resulting in failure on our side as our unix system does not support it.
Have raised an issue on the same, can you take a look.

https://github.com/appleboy/scp-action/issues/119
